version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./backend/storage/dbdata:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge